version: 0.1.0_alpha
infrastructure_engineer_role_name: pintek-infrastructure-engineer
network_engineer_role_name: pintek-network-engineer
enterprise_architect: pintek-enterprise-architect

service_name: siem
vpc_key: management
